### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Taknax** [MCreator-Examples/Projects#39]
Hi, i used your tutorial to make an alloy furnace in mcreator 2022.1 and it works suprisingly good. But i have an issue. My Furnace has 4 slots, not 3. So i just doubled the "tagged in item tags as" line in "AlloyFurnaceUpdateTick and AlloyFurnaceOnUpdateTick". I changed the numbers for the slots and created recipes ofc.
The result is it is working, but it is bugging. I tagged all items (ingots like tin, zinc and brass) as "furnace:furnace/recipe_item". But if i put in an illegal item in the furnace, which are tagged, then it starts to work with no result. After that it dupes the ingredient, if i change the items to make another alloy.
Here is my procedure. I use the translator and cant tell you exactly what i mean. Maybe it is easier if you see what i mean.
Whatever. Thank you for the nice tutorial. It helped me much.
I wish you the best, health and peace
Taknax

The Procedure
[AlloyFurnaceUpdateTick.ptpl.zip](https://github.com/MCreator-Examples/Projects/files/9277096/AlloyFurnaceUpdateTick.ptpl.zip)

Shareable Zip
[AlloyFurnace+.zip](https://github.com/MCreator-Examples/Projects/files/9277109/AlloyFurnace%2B.zip)

Screenshots of the idea.
![2022-08-07_16 31 42](https://user-images.githubusercontent.com/66703017/183300397-9ea9dc09-a3b2-431e-8866-0dabecca9775.png)
![2022-08-07_16 35 42](https://user-images.githubusercontent.com/66703017/183300413-88da4891-e4d7-4535-9d06-3a78220e32bf.png)

**Comment by northwesttreesgaming** [comment]
Chaning the slots are up to the creator to tinker with. I simply can't help everyone with each GUI, there is just to many combonations where it would eat up my time.

I suggest to ask for help on the MCToolkit discord server under the #mcreator-help channel.
We have some moderators that like to help and there are one or two other community members that do too.

Here is the link for that discord server.
https://discord.gg/D4dUwXmTkN
