### ISSUE TITLE
Custom button in GUIs

### ISSUE THREAD

**Issue by andryqx** [MCreator-Examples/Projects#57]
### Feature overview

with the help of this custom code, the player can create his own custom buttons on 1.17.1, but how to make the code work on 1.16.5 as well?

### Feature checklist

1. the player will be able to create an interface with his own clickable button with any textures for any size. ( on 1.16.5 )

### Files and Sources

https://mcreator.net/forum/83507/added-image-buttons-guis - tutorial for 1.17.1, but it don't work on 1.16.5

### BEFORE YOU POST! Please do the following.

- [X] I have looked if the feature as been requested already on the issue tab and could not find a similar issue.
- [X] I have have searched NorthWestTrees Gaming's MCreator Playlists and could not find the feature I want
- [X] I understand that not all things are possible and that the tutorial may not be made any time soon or at all

**Comment by northwesttreesgaming** [comment]
Currently, there is no support for custom buttons without hand-coding them.
And even then I only record for the latest version of MCreator, so 1.16.5 is not supported for tutorials by NWTG anymore.
