### ISSUE TITLE
Crops v3 Procedures can't be imported

### ISSUE THREAD

**Issue by PaperMacho** [MCreator-Examples/Projects#8]
When trying to import the CropUpdateTick and CropGrowthScoreCondition ptpl procedures into mcreator 2021.3 only the variable names are imported. The code blocks do not get imported and there are no errors reported ny mcreator.

Opening up the crops workspace included in the zip file, those procedures also fail to build:

Build Log Attached

[crops_v3_build_error.txt](https://github.com/MCreator-Examples/Projects/files/8193249/crops_v3_build_error.txt)

**Comment by northwesttreesgaming** [comment]
It may require the this plugin.
https://mcreator.net/plugin/78808/blockstate-procedures

If it works let me know here and I will add a note to the tutorial video and the download page.

**Comment by northwesttreesgaming** [comment]
I closed the issue due to no follow up on the issue I am presuming that the suggestion fixed the issue.
